### ISSUE TITLE
.

### ISSUE THREAD

**Issue by edysfunction** [ijgnd/anki__syntax-highlighting#3]

**Comment by ijgnd** [comment]
where does the highlighting happens: In the pop-up or in the original card (when pop-ups are active). But in both ways I can't reproduce the problem. But this doesn't say much ...

What do you mean by "code blocks". text that is surrounded just with the html "code" tag or any colored code block from my add-on? If it's the former does this also happen if you add the html tag without my add-on directly into the source code. If it's the latter: Does this also happen with snippets made with the original "Syntax Highlighting" add-on?

&nbsp;

Disable all add-ons except for the pop-up dictionary, restart Anki and try again. Does this problem persist in the latest Anki version (2.1.35)?

If not: it's a conflict with another add-on: I would disable/enable half of your add-ons, restart,  and try again and so on.

If it remains: Maybe it's your styling so you could try with a code block on an unchanged basic note type. 

You could share some affected notes so that I can reproduce it.

&nbsp;

But at the moment I'm quite busy so it's low priority for me so that it might take some weeks or months. Maybe it's easier to just ignore it.

**Comment by edysfunction** [comment]
Thank you for looking into it! 

I'm completely new to coding and github so I'm very sorry for my wrong use of terminology, the unclear descriptions, etc.

It's just about the yellow background of the code ('egre' in my screenshot) on the anki card - somehow the default grey background gets replaced by the highlighted background from the pop-up dictionary (see 'sorbitol' ![grafik](https://user-images.githubusercontent.com/69192992/101344901-8a2e5f00-3886-11eb-939a-6fd592135054.png)). My uneducated guess is that <div class="highlight"> somehow gets a new background color assigned by the pop-up addon.

I already found a nice fix: I switched to dark mode and now everything looks fine again. It seems only affect the light mode in Anki. And yes, it's a minor detail.

**Comment by ijgnd** [comment]
> My uneducated guess is that < div class="highlight" > somehow gets a new background color assigned by the pop-up addon.

I think that's much more than "uneducated" ...

At the moment I don't know how to work around this. 

Maybe replace all occurrences of the string highlight in the popup-dictionary with the term "p_highlight"? In my add-on I guess you could use the setting "css_custom_class_per_style" but then all future css changes are more complicated. 

&nbsp;

About bug reports for my add-ons: Most people don't seem to realize that usually the fix is quick and simple and the most time consuming task is to narrow down the problem. With this a detailed bug report helps a lot. This also increases the chance of getting a fix a lot. For the person reporting the bug it's usually easier to provide a minimal setup to reproduce the bug.
